version: '3.8'

services:
  app:
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE=false
    volumes:
      - ~/.vsdbg:/root/.vsdbg:rw
      - .:/app:cached
    command: tail -f /dev/null

  fileapi:
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    volumes:
      - ~/.vsdbg:/root/.vsdbg:rw
      - .:/app:cached
    command: tail -f /dev/null

  captcha_service:
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    volumes:
      - ~/.vsdbg:/root/.vsdbg:rw
      - .:/app:cached
    command: tail -f /dev/null
