version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: CommentSystem/Dockerfile
    ports:
      - "5000:5000" # HTTP порт
      - "5001:5001" # HTTPS порт
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=CommentSystemDB;User Id=CommentSystemAdmin;Password=CommentSystem!2025;TrustServerCertificate=True      
      - ConnectionStrings__Redis=redis:6379
      - ConnectionStrings__RabbitMQ=amqp://CommentSystemAdmin:CommentSystem!2025@rabbitmq:5672
    depends_on:
      - db
      - redis
      - rabbitmq
    restart: always

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "CommentSystem!2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    volumes:
      - mssql_data:/var/opt/mssql
    restart: always

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    command: ["redis-server"]
    restart: always

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq_server
    hostname: rabbitmq
    ports:
      - "5672:5672"   # AMQP (для .NET)
      - "15672:15672" # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: CommentSystemAdmin
      RABBITMQ_DEFAULT_PASS: CommentSystem!2025
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

volumes:
  mssql_data:
  rabbitmq_data:
