# Используем .NET 9 SDK для сборки
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app

# Copy project file and restore dependencies
COPY . .
RUN dotnet restore
RUN dotnet publish -c Release -o /out

# Use .NET 9 runtime for running the app
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app
COPY --from=build /out ./

# Runn app
ENTRYPOINT ["dotnet", "FileServiceAPI.dll"]
